export {Dashboard} from '@styled-icons/boxicons-solid/Dashboard'
export {Home} from '@styled-icons/boxicons-regular/Home'
export {ShoppingBag} from '@styled-icons/boxicons-solid/ShoppingBag'
export {Favorite} from '@styled-icons/material/Favorite'
export {TrendingUp} from '@styled-icons/boxicons-regular/TrendingUp'
export {Star} from '@styled-icons/bootstrap/Star'
export {PurchaseTag} from '@styled-icons/boxicons-solid/PurchaseTag'
export {Settings} from '@styled-icons/evaicons-solid/Settings'